export interface MirrorWorldIcon {
    id: string;
    label: string;
    path: string;
}
export const MIRROR_WORLD_ICONS: MirrorWorldIcon[] = [
    { id: 'fallen_la_manchaland', label: 'Fallen La Manchaland', path: '/icons/mirror/World_of_Fallen_La_Manchaland_Icon.png' },
    { id: 'fanghunt_office', label: 'Fanghunt Office', path: '/icons/mirror/World_of_Fanghunt_Office_Icon.png' },
    { id: 'firefist_office', label: 'Firefist Office', path: '/icons/mirror/World_of_Firefist_Office_Icon.png' },
    { id: 'h_corp', label: 'H Corp.', path: '/icons/mirror/World_of_H_Corp._Icon.png' },
    { id: 'k_corp', label: 'K Corp.', path: '/icons/mirror/World_of_K_Corp._Icon.png' },
    { id: 'l_corp', label: 'L Corp.', path: '/icons/mirror/World_of_L_Corp._Icon.png' },
    { id: 'la_manchaland', label: 'La Manchaland', path: '/icons/mirror/World_of_La_Manchaland_Icon.png' },
    { id: 'lccb', label: 'LCCB', path: '/icons/mirror/World_of_LCCB_Icon.png' },
    { id: 'lobotomy_corp_hq_1', label: 'Lobotomy Corporation HQ - 1', path: '/icons/mirror/World_of_Lobotomy_Corporation_Headquarters_-_1_Icon.png' },
    { id: 'molar_office', label: 'Molar Office', path: '/icons/mirror/World_of_Molar_Office_Icon.png' },
    { id: 'multicrack_office', label: 'MultiCrack Office', path: '/icons/mirror/World_of_MultiCrack_Office_Icon.png' },
    { id: 'n_corp', label: 'N Corp.', path: '/icons/mirror/World_of_N_Corp._Icon.png' },
    { id: 'n_corp_fanatics', label: 'N Corp. Fanatics', path: '/icons/mirror/World_of_N_Corp._Fanatics_Icon.png' },
    { id: 'r_corp', label: 'R Corp.', path: '/icons/mirror/World_of_R_Corp._Icon.png' },
    { id: 't_corp', label: 'T Corp.', path: '/icons/mirror/World_of_T_Corp._Icon.png' },
    { id: 'u_corp', label: 'U Corp.', path: '/icons/mirror/World_of_U_Corp._Icon.png' },
    { id: 'usurped_h_corp', label: 'Usurped H Corp.', path: '/icons/mirror/World_of_Usurped_H_Corp._Icon.png' },
    { id: 'w_corp', label: 'W Corp.', path: '/icons/mirror/World_of_W_Corp._Icon.png' },
    { id: 'wuthering_heights', label: 'Wuthering Heights', path: '/icons/mirror/World_of_Wuthering_Heights_Icon.png' },
    { id: 'cinq_eastern', label: 'Cinq Assoc. Eastern Branch', path: '/icons/mirror/World_of_the_Cinq_Association_Eastern_Branch_Icon.png' },
    { id: 'cinq_southern', label: 'Cinq Assoc. Southern Branch', path: '/icons/mirror/World_of_the_Cinq_Association_Southern_Branch_Icon.png' },
    { id: 'cinq_western', label: 'Cinq Assoc. Western Branch', path: '/icons/mirror/World_of_the_Cinq_Association_Western_Branch_Icon.png' },
    { id: 'devyat_northern', label: "Devyat' Assoc. Northern Branch", path: "/icons/mirror/World_of_the_Devyat'_Association_Northern_Branch_Icon.png" },
    { id: 'dieci_southern', label: 'Dieci Assoc. Southern Branch', path: '/icons/mirror/World_of_the_Dieci_Association_Southern_Branch_Icon.png' },
    { id: 'district_20', label: 'District 20 Backstreets', path: '/icons/mirror/World_of_the_District_20_Backstreets_Icon.png' },
    { id: 'district_21', label: 'District 21 Backstreets', path: '/icons/mirror/World_of_the_District_21_Backstreets_Icon.png' },
    { id: 'district_23', label: 'District 23 Backstreets', path: '/icons/mirror/World_of_the_District_23_Backstreets_Icon.png' },
    { id: 'former_g_corp', label: 'Former G Corp.', path: '/icons/mirror/World_of_the_Former_G_Corp._Icon.png' },
    { id: 'former_library_guests_1', label: 'Former Library Guests - 1', path: '/icons/mirror/World_of_the_Former_Library_Guests_-_1_Icon.png' },
    { id: 'house_of_spiders', label: 'House of Spiders', path: '/icons/mirror/World_of_the_House_of_Spiders_Icon.png' },
    { id: 'the_index', label: 'The Index', path: '/icons/mirror/World_of_the_Index_Icon.png' },
    { id: 'j_corp_backstreets', label: 'J Corp. Backstreets', path: '/icons/mirror/World_of_the_J_Corp._Backstreets_Icon.png' },
    { id: 'kurokumo_clan', label: 'Kurokumo Clan', path: '/icons/mirror/World_of_the_Kurokumo_Clan_Icon.png' },
    { id: 'kurokumo_blade_lineage', label: 'Kurokumo Clan & Blade Lineage', path: '/icons/mirror/World_of_the_Kurokumo_Clan_and_Blade_Lineage_Icon.png' },
    { id: 'lca', label: 'LCA', path: '/icons/mirror/World_of_the_LCA_Icon.png' },
    { id: 'lce', label: 'LCE', path: '/icons/mirror/World_of_the_LCE_Icon.png' },
    { id: 'liu_southern', label: 'Liu Assoc. Southern Branch', path: '/icons/mirror/World_of_the_Liu_Association_Southern_Branch_Icon.png' },
    { id: 'the_middle', label: 'The Middle', path: '/icons/mirror/World_of_the_Middle_Icon.png' },
    { id: 'the_ring', label: 'The Ring', path: '/icons/mirror/World_of_the_Ring_Icon.png' },
    { id: 'seven_southern', label: 'Seven Assoc. Southern Branch', path: '/icons/mirror/World_of_the_Seven_Association_Southern_Branch_Icon.png' },
    { id: 'shi_eastern', label: 'Shi Assoc. Eastern Branch', path: '/icons/mirror/World_of_the_Shi_Association_Eastern_Branch_Icon.png' },
    { id: 'shi_southern', label: 'Shi Assoc. Southern Branch', path: '/icons/mirror/World_of_the_Shi_Association_Southern_Branch_Icon.png' },
    { id: 'the_thumb', label: 'The Thumb', path: '/icons/mirror/World_of_the_Thumb_Icon.png' },
    { id: 'zwei_southern', label: 'Zwei Assoc. Southern Branch', path: '/icons/mirror/World_of_the_Zwei_Association_Southern_Branch_Icon.png' },
    { id: 'zwei_western', label: 'Zwei Assoc. Western Branch', path: '/icons/mirror/World_of_the_Zwei_Association_Western_Branch_Icon.png' },
    { id: 'oufi_southern', label: 'Öufi Assoc. Southern Branch', path: '/icons/mirror/World_of_the_Öufi_Association_Southern_Branch_Icon.png' },
];
